# swarm集群，启动命令为：docker stack deploy wordpress --compose-file=docker-swarm.yml
version: "3.7"
volumes:
  wp-data:
networks:
  wp-back:
    driver: overlay
services:
  web:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-pass
    networks:
      - wp-back
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
    volumes:
      - wp-data:/var/lib/mysql
    networks:
      - wp-back
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
