version: "3.7"
volumes:
  wp-data:
networks:
  wp-back:
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp-pass
    networks:
      - wp-back
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
    volumes:
      - $PWD/mysql:/var/lib/mysql # 数据库文件映射到当前目录下
    networks:
      - wp-back
